catalogs:
  content:
    '@nuxt/content': ^3.7.1
    '@nuxtjs/seo': ^3.2.2
    '@shikijs/colorized-brackets': ^3.13.0
    '@shikijs/transformers': ^3.13.0
    plain-shiki: ^0.3.1
    rehype-katex: ^7.0.1
    remark-math: ^6.0.0
    remark-reading-time: ^2.0.2
    shiki: ^3.13.0
  framework:
    '@dxup/nuxt': ^0.0.1
    ci-info: ^4.3.0
    cross-env: ^10.0.0
    nuxt: ^4.1.2
    sass-embedded: ^1.93.2
    typescript: ^5.9.2
    unplugin-yaml: ^3.0.6
    vue: ^3.5.22
    vue-router: ^4.5.1
  quality:
    '@antfu/eslint-config': ^5.4.1
    '@zinkawaii/stylelint-config': ^0.3.3
    cspell: ^9.2.1
    eslint: ^9.36.0
    stylelint: ^16.24.0
  ui:
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/ph': ^1.2.2
    '@nuxt/icon': ^2.0.0
    '@nuxt/image': ^1.11.0
    '@nuxtjs/color-mode': ^3.5.2
    embla-carousel-autoplay: ^8.6.0
    embla-carousel-vue: ^8.6.0
    embla-carousel-wheel-gestures: ^8.1.0
    vue-tippy: ^6.7.1
    vue-virtual-scroller: 2.0.0-beta.8
  util:
    '@clack/prompts': ^0.11.0
    '@pinia/nuxt': ^0.11.2
    '@vueuse/core': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    '@vueuse/router': 14.0.0-alpha.0
    date-fns: ^4.1.0
    date-fns-tz: ^3.2.0
    fast-xml-parser: ^5.2.5
    minisearch: ^7.2.0
    nanoid: ^5.1.6
    oxc-minify: ^0.92.0
    p-limit: ^7.1.1
    parse-domain: ^8.2.2
    radash: ^12.1.1
    rimraf: ^6.0.1
    strip-ansi: ^7.1.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - oxc-resolver
  - rolldown
  - sharp
  - unrs-resolver

overrides:
  sharp: 0.33.4

patchedDependencies:
  '@nuxtjs/mdc': patches/@nuxtjs__mdc.patch
  '@vue/shared': patches/@vue__shared.patch

shamefullyHoist: true
